package seen.kai.telegram.state;

public enum BotState {
    IDLE,
    WAITING_PASSWORD,
    WAITING_DELETE_PASSWORD,
    WAITING_START_MONTH,
    WAITING_START_DATE,
    WAITING_END_DATE,
    WAITING_DEPARTURE_CITY,
    WAITING_DEPARTURE_CITY_TEXT,
    WAITING_ARRIVAL_CITY,
    WAITING_ARRIVAL_CITY_TEXT,
    WAITING_ORIGINATION,
    WAITING_ORIGINATION_TEXT,
    WAITING_DESTINATION,
    WAITING_DESTINATION_TEXT,
    WAITING_MAX_PRICE,
    WAITING_CONFIRMATION
}
