package seen.kai.telegram.service;

import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;
import org.eclipse.microprofile.config.inject.ConfigProperty;
import org.jboss.logging.Logger;
import org.telegram.telegrambots.meta.api.objects.CallbackQuery;
import org.telegram.telegrambots.meta.api.objects.Update;
import org.telegram.telegrambots.meta.api.objects.replykeyboard.InlineKeyboardMarkup;
import org.telegram.telegrambots.meta.api.objects.replykeyboard.buttons.InlineKeyboardRow;
import org.telegram.telegrambots.meta.api.objects.replykeyboard.buttons.InlineKeyboardButton;
import org.telegram.telegrambots.meta.api.objects.message.Message;
import seen.kai.checker.service.StationService;
import seen.kai.subscription.dto.request.SubscriptionRequest;
import seen.kai.subscription.dto.response.SubscriptionResponse;
import seen.kai.subscription.entity.TicketSubscription;
import seen.kai.subscription.service.SubscriptionService;
import seen.kai.telegram.state.BotState;
import seen.kai.telegram.state.SubscriptionDraft;

import java.time.LocalDate;
import java.time.Month;
import java.time.YearMonth;
import java.time.format.DateTimeFormatter;
import java.time.format.TextStyle;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.concurrent.ConcurrentHashMap;
import java.util.regex.Pattern;

@ApplicationScoped
public class TelegramBotService {
    private static final Logger LOG = Logger.getLogger(TelegramBotService.class);
    private static final Pattern DIGITS_ONLY = Pattern.compile("^\\d+$");
    private static final List<String> COMMON_STATIONS = List.of("KM", "PSE", "GMR");
    private static final Locale ID_LOCALE = Locale.forLanguageTag("id-ID");
    private static final DateTimeFormatter DISPLAY_DATE = DateTimeFormatter.ofPattern("d MMM", ID_LOCALE);

    // This class is a small state machine for one Telegram chat session.
    // Updates are delivered by our webhook controller and routed to handleUpdate(...).
    private final SubscriptionService subscriptionService;
    private final StationService stationService;
    // Per chat_id draft state. Key is String (Telegram chat id), value stores the wizard progress.
    // TODO: Implement Redis For User Session
    private final ConcurrentHashMap<String, SubscriptionDraft> sessions = new ConcurrentHashMap<>();

    @Inject
    TelegramApiService telegramApi;

    @ConfigProperty(name = "kai.subscription.password", defaultValue = "")
    String subscriptionPassword;

    public TelegramBotService(SubscriptionService subscriptionService, StationService stationService) {
        this.subscriptionService = subscriptionService;
        this.stationService = stationService;
    }

    // Main entry point for webhook updates (message or callback query).
    public void handleUpdate(Update update) {
        if (update == null) {
            return;
        }

        // Handle inline keyboard button.
        if (update.hasCallbackQuery()) {
            handleCallback(update.getCallbackQuery());
            return;
        }

        // Handle regular chat messages (Text Only).
        if (update.hasMessage()) {
            handleMessage(update.getMessage());
        }
    }

    // Handles callback query updates generated by inline keyboard buttons.
    private void handleCallback(CallbackQuery callbackQuery) {
        // Callback must include the original message (for chat_id + message_id).
        if (callbackQuery == null || callbackQuery.getMessage() == null) {
            return;
        }

        String callbackData = callbackQuery.getData();
        String chatId = String.valueOf(callbackQuery.getMessage().getChatId());
        Integer messageId = callbackQuery.getMessage().getMessageId();
        answerCallback(callbackQuery.getId());

        if (chatId.isBlank() || callbackData == null || callbackData.isBlank()) {
            return;
        }

        // Callback data conventions:
        // - menu:* : main menu actions
        // - act:*  : flow control (cancel/save)
        // - sm/sd/ed : start month/start date/end date selection
        // - org/dst/mp : origin/desination station and max price selection

        // Start a new subscription flow (wizard).
        if ("menu:new".equals(callbackData)) {
            SubscriptionDraft draft = new SubscriptionDraft();
            // If password is configured, require it before allowing subscription creation.
            if (subscriptionPassword != null && !subscriptionPassword.isBlank()) {
                draft.setState(BotState.WAITING_PASSWORD);
                draft.setPasswordVerified(false);
                sessions.put(chatId, draft);
                editMessage(chatId, messageId, "Masukkan password untuk membuat subscription:", null);
                return;
            }

            draft.setPasswordVerified(true);
            draft.setState(BotState.WAITING_START_MONTH);
            sessions.put(chatId, draft);
            editMessage(chatId, messageId, "Pilih bulan mulai:", monthKeyboard());
            return;
        }

        // Cancel current flow and return to main menu.
        if ("act:cancel".equals(callbackData)) {
            sessions.remove(chatId);
            editMessage(chatId, messageId, "Submission subscription batal.", mainMenuKeyboard());
            return;
        }

        // Keep a draft even if user presses buttons out of order; we validate inputs per state.
        SubscriptionDraft draft = sessions.computeIfAbsent(chatId, ignored -> new SubscriptionDraft());

        // Start month selection.
        if (callbackData.startsWith("sm:")) {
            int month = parseIntSafely(callbackData.substring(3));
            int currentMonth = LocalDate.now().getMonthValue();
            // Reject months in the past (current year) or outside calendar range.
            if (month < currentMonth || month > 12) {
                editMessage(chatId, messageId, "Bulan tidak valid.", monthKeyboard());
                return;
            }
            draft.setStartMonth(month);
            draft.setState(BotState.WAITING_START_DATE);
            editMessage(chatId, messageId, "Pilih tanggal mulai:", startDateKeyboardForMonth(month));
            return;
        }

        // Start date selection.
        if (callbackData.startsWith("sd:")) {
            LocalDate startDate = parseLocalDate(callbackData.substring(3));
            // Start date must be today or later, and within current year.
            if (startDate == null || startDate.getYear() != LocalDate.now().getYear() || startDate.isBefore(LocalDate.now())) {
                editMessage(chatId, messageId, "Tanggal mulai tidak valid.", monthKeyboard());
                return;
            }
            draft.setStartDate(startDate);
            draft.setState(BotState.WAITING_END_DATE);
            editMessage(chatId, messageId, "Pilih tanggal akhir (maks 5 hari):", endDateKeyboard(startDate));
            return;
        }

        // End date selection.
        if (callbackData.startsWith("ed:")) {
            LocalDate endDate = parseLocalDate(callbackData.substring(3));
            LocalDate startDate = draft.getStartDate();
            // End date requires a start date; reject missing/invalid values.
            if (endDate == null || startDate == null) {
                editMessage(chatId, messageId, "Tanggal akhir tidak valid.", monthKeyboard());
                return;
            }
            // End date must be within 0..5 days from start date (and current year).
            if (endDate.isBefore(startDate) || endDate.isAfter(startDate.plusDays(5)) || endDate.getYear() != LocalDate.now().getYear()) {
                editMessage(chatId, messageId, "Tanggal akhir harus dalam rentang 0..5 hari dari tanggal mulai.", endDateKeyboard(startDate));
                return;
            }
            draft.setEndDate(endDate);
            draft.setState(BotState.WAITING_ORIGINATION);
            editMessage(chatId, messageId, "Pilih origination:", stationKeyboard("org"));
            return;
        }

        // Switch origination input to manual text.
        if ("org:manual".equals(callbackData)) {
            draft.setState(BotState.WAITING_ORIGINATION_TEXT);
            editMessage(chatId, messageId, "Ketik kode origination manual (contoh: KM).", null);
            return;
        }

        // Origination selection from buttons.
        if (callbackData.startsWith("org:")) {
            String code = callbackData.substring(4).trim().toUpperCase(Locale.ROOT);
            StationService.Station station = stationService.findByCode(code).orElse(null);
            draft.setOrigination(station != null ? station.code() : code);
            draft.setState(BotState.WAITING_DESTINATION);
            editMessage(chatId, messageId, "Pilih destination:", stationKeyboard("dst"));
            return;
        }

        // Switch destination input to manual text.
        if ("dst:manual".equals(callbackData)) {
            draft.setState(BotState.WAITING_DESTINATION_TEXT);
            editMessage(chatId, messageId, "Ketik kode destination manual (contoh: PSE).", null);
            return;
        }
        // Destination selection from buttons.
        if (callbackData.startsWith("dst:")) {
            String code = callbackData.substring(4).trim().toUpperCase(Locale.ROOT);
            StationService.Station station = stationService.findByCode(code).orElse(null);
            draft.setDestination(station != null ? station.code() : code);
            draft.setState(BotState.WAITING_MAX_PRICE);
            editMessage(chatId, messageId, "Pilih max price:", maxPriceKeyboard());
            return;
        }

        // Max price selection.
        if (callbackData.startsWith("mp:")) {
            // Switch max price input to manual numeric text.
            if ("mp:manual".equals(callbackData)) {
                draft.setState(BotState.WAITING_MAX_PRICE);
                editMessage(chatId, messageId, "Ketik max price (contoh: 350000).", null);
                return;
            }
            int maxPrice = parseIntSafely(callbackData.substring(3));
            // Price must be a positive integer.
            if (maxPrice <= 0) {
                editMessage(chatId, messageId, "max price tidak valid. Pilih tombol atau ketik angka.", maxPriceKeyboard());
                return;
            }
            draft.setMaxPrice(maxPrice);
            draft.setState(BotState.WAITING_CONFIRMATION);
            editMessage(chatId, messageId, buildSummary(draft), confirmationKeyboard());
            return;
        }

        // Persist the draft to DB (creates or attaches subscription).
        if ("act:save".equals(callbackData)) {
            saveDraft(chatId, messageId, draft);
        }
    }

    // Handles regular chat messages. This bot is command-driven plus a wizard flow for manual inputs.
    private void handleMessage(Message message) {
        // Only process text messages that include chat_id.
        if (message == null || message.getChatId() == null || message.getText() == null) {
            return;
        }

        String chatId = String.valueOf(message.getChatId());
        String text = message.getText().trim();
        // Ignore empty/whitespace-only text.
        if (text.isBlank()) {
            return;
        }

        // Reset to main menu (also clears any in-progress wizard state).
        if ("/start".equalsIgnoreCase(text)) {
            sessions.remove(chatId);
            sendMessage(chatId, "Pilih menu:", mainMenuKeyboard());
            return;
        }

        // Start delete flow (requires server-side password to be set).
        if ("/delete".equalsIgnoreCase(text)) {
            // Delete is disabled unless password is configured on the server.
            if (subscriptionPassword == null || subscriptionPassword.isBlank()) {
                sendMessage(chatId, "Delete dinonaktifkan: server belum set kai.subscription.password.", null);
                return;
            }

            List<TicketSubscription> subscriptions = subscriptionService.findAllByChatId(chatId);
            // Nothing to delete for this chat.
            if (subscriptions.isEmpty()) {
                sendMessage(chatId, "Tidak ada subscription untuk chat ini.", mainMenuKeyboard());
                return;
            }

            // This flow deletes the first subscription for the chat (current behavior).
            TicketSubscription target = subscriptions.getFirst();
            SubscriptionDraft draft = new SubscriptionDraft();
            draft.setState(BotState.WAITING_DELETE_PASSWORD);
            draft.setPasswordVerified(false);
            draft.setPendingDeleteSubscriptionId(target.getId());
            draft.setPendingDeleteSummary(buildSubscriptionSummary(target));
            sessions.put(chatId, draft);
            sendMessage(chatId, "Masukkan password untuk menghapus subscription ini:\n\n" + draft.getPendingDeleteSummary(), null);
            return;
        }

        // List existing subscriptions for this chat.
        if ("/list".equalsIgnoreCase(text)) {
            List<TicketSubscription> subscriptions = subscriptionService.findAllByChatId(chatId);
            // No subscriptions to show.
            if (subscriptions.isEmpty()) {
                sendMessage(chatId, "Tidak ada subscription untuk chat ini.", mainMenuKeyboard());
                return;
            }
            StringBuilder out = new StringBuilder();
            out.append("Daftar subscription ").append(chatId).append("):\n\n");
            for (TicketSubscription subscription : subscriptions) {
                out.append("ID: ").append(subscription.getId()).append("\n")
                        .append("Tanggal: ").append(subscription.getStartDate()).append(" s/d ").append(subscription.getEndDate()).append("\n")
                        .append("Rute: ").append(subscription.getOrigination()).append(" -> ").append(subscription.getDestination()).append("\n")
                        .append("Max price: ").append(subscription.getMaxPrice()).append("\n\n");
            }
            sendMessage(chatId, out.toString().trim(), mainMenuKeyboard());
            return;
        }

        // Cancel the current wizard session for this chat.
        if ("/cancel".equalsIgnoreCase(text)) {
            sessions.remove(chatId);
            sendMessage(chatId, "Flow dibatalkan.", mainMenuKeyboard());
            return;
        }

        SubscriptionDraft draft = sessions.get(chatId);

        // No active session means the user must start a new flow via the menu.
        if (draft == null) {
            sendMessage(chatId, "Ketik /new untuk buat subscription baru.", mainMenuKeyboard());
            return;
        }

        // Delete password step: verify password then perform delete.
        if (draft.getState() == BotState.WAITING_DELETE_PASSWORD) {
            // Password match is required before any deletion.
            if (subscriptionPassword != null && !subscriptionPassword.isBlank() && subscriptionPassword.equals(text)) {
                Long subscriptionId = draft.getPendingDeleteSubscriptionId();
                boolean deleted = subscriptionId != null && subscriptionId > 0
                        ? subscriptionService.deleteForChatId(subscriptionId, chatId)
                        : subscriptionService.deleteForChatId(chatId);
                sessions.remove(chatId);
                // Delete can fail if the subscription no longer exists or is not attached to this chat.
                if (!deleted) {
                    sendMessage(chatId, "Gagal delete: subscription tidak ditemukan untuk chat ini.", mainMenuKeyboard());
                    return;
                }
                String deletedSummary = draft.getPendingDeleteSummary();
                // Fallback message if we don't have a stored summary.
                if (deletedSummary == null || deletedSummary.isBlank()) {
                    deletedSummary = "Subscription terhapus.";
                }
                sendMessage(chatId, "Subscription terhapus:\n\n" + deletedSummary, mainMenuKeyboard());
                return;
            }
            // Wrong password: keep the state so the user can retry.
            sendMessage(chatId, "Password salah. Coba lagi atau /cancel.", null);
            return;
        }

        // Create password step: verify password before allowing subscription creation.
        if (draft.getState() == BotState.WAITING_PASSWORD) {
            // Password match advances the wizard to month selection.
            if (subscriptionPassword != null && !subscriptionPassword.isBlank() && subscriptionPassword.equals(text)) {
                draft.setPasswordVerified(true);
                draft.setState(BotState.WAITING_START_MONTH);
                sendMessage(chatId, "Password OK. Pilih bulan mulai (tahun otomatis):", monthKeyboard());
                return;
            }
            // Wrong password: keep the state so the user can retry.
            sendMessage(chatId, "Password salah. Coba lagi atau /cancel.", null);
            return;
        }

        // Manual origination code entry.
        if (draft.getState() == BotState.WAITING_ORIGINATION_TEXT) {
            String station = normalizeStation(text);
            // Station code must be short and non-empty (format validation).
            if (station == null) {
                sendMessage(chatId, "Kode origination tidak valid.", null);
                return;
            }
            StationService.Station resolved = stationService.findByCode(station).orElse(null);
            // Station code must exist in our known station list.
            if (resolved == null) {
                sendMessage(chatId, "Kode origination tidak ditemukan di KAI (api/stations2).", null);
                return;
            }
            draft.setOrigination(resolved.code());
            draft.setState(BotState.WAITING_DESTINATION);
            sendMessage(chatId, "Pilih destination:", stationKeyboard("dst"));
            return;
        }

        // Manual destination code entry.
        if (draft.getState() == BotState.WAITING_DESTINATION_TEXT) {
            String station = normalizeStation(text);
            // Station code must be short and non-empty (format validation).
            if (station == null) {
                sendMessage(chatId, "Kode destination tidak valid.", null);
                return;
            }
            StationService.Station resolved = stationService.findByCode(station).orElse(null);
            // Station code must exist in our known station list.
            if (resolved == null) {
                sendMessage(chatId, "Kode destination tidak ditemukan di KAI (api/stations2).", null);
                return;
            }
            draft.setDestination(resolved.code());
            draft.setState(BotState.WAITING_MAX_PRICE);
            sendMessage(chatId, "Pilih max price (atau ketik angka):", maxPriceKeyboard());
            return;
        }

        // Manual max price entry: only accept digits when we're waiting for max price.
        if (draft.getState() == BotState.WAITING_MAX_PRICE && DIGITS_ONLY.matcher(text).matches()) {
            int value = parseIntSafely(text);
            // Price must be positive.
            if (value > 0) {
                draft.setMaxPrice(value);
                draft.setState(BotState.WAITING_CONFIRMATION);
                sendMessage(chatId, buildSummary(draft), confirmationKeyboard());
                return;
            }
        }

        // Fallback: input does not match the expected state.
        sendMessage(chatId, "Input tidak sesuai state saat ini. Gunakan tombol atau /cancel.", null);
    }

    // Persists the draft as a subscription (create new or attach chat to existing subscription).
    private void saveDraft(String chatId, Integer messageId, SubscriptionDraft draft) {
        try {
            // If password is configured, require it to have been verified in the wizard.
            if (subscriptionPassword != null && !subscriptionPassword.isBlank() && !draft.isPasswordVerified()) {
                editMessage(chatId, messageId, "Password belum diverifikasi. Ketik /new untuk mulai lagi.", mainMenuKeyboard());
                return;
            }
            // Build request DTO and delegate persistence/validation to SubscriptionService.
            SubscriptionRequest request = new SubscriptionRequest(
                    draft.getStartDate(),
                    draft.getEndDate(),
                    draft.getOrigination(),
                    draft.getDestination(),
                    draft.getMaxPrice(),
                    chatId,
                    subscriptionPassword
            );
            SubscriptionResponse response = subscriptionService.createOrAttach(request);
            // Clear wizard session after successful save.
            sessions.remove(chatId);
            editMessage(
                    chatId,
                    messageId,
                    "Subscription tersimpan.\n"
                            + "ID: " + response.id() + "\n"
                            + "Rute: " + response.origination() + " -> " + response.destination() + "\n"
                            + "Rentang tanggal: " + response.startDate() + " s/d " + response.endDate() + "\n"
                            + "Max price: " + response.maxPrice(),
                    mainMenuKeyboard()
            );
        } catch (IllegalArgumentException e) {
            // Validation / business rule errors are shown to user.
            editMessage(chatId, messageId, "Gagal simpan: " + e.getMessage(), confirmationKeyboard());
        } catch (Exception e) {
            // Unexpected errors should be logged server-side; user gets a generic message.
            LOG.error("Gagal simpan subscription dari Telegram bot", e);
            editMessage(chatId, messageId, "Terjadi error saat simpan subscription.", confirmationKeyboard());
        }
    }

    // Builds a short confirmation text shown before the user presses "Simpan".
    private String buildSummary(SubscriptionDraft draft) {
        return "Konfirmasi subscription:\n"
                + "start_date: " + draft.getStartDate() + "\n"
                + "end_date: " + draft.getEndDate() + "\n"
                + "origination: " + draft.getOrigination() + "\n"
                + "destination: " + draft.getDestination() + "\n"
                + "max_price: " + draft.getMaxPrice();
    }

    // Builds a compact summary used for delete confirmation.
    private String buildSubscriptionSummary(TicketSubscription subscription) {
        return "ID: " + subscription.getId() + "\n"
                + "Tanggal: " + subscription.getStartDate() + " s/d " + subscription.getEndDate() + "\n"
                + "Rute: " + subscription.getOrigination() + " -> " + subscription.getDestination() + "\n"
                + "Max price: " + subscription.getMaxPrice();
    }

    // Inline keyboard helpers.
    // telegrambots-meta 9.5.0 models keyboards as List<InlineKeyboardRow> (not List<List<Button>>).
    // Main menu keyboard shown on /start and after successful operations.
    private InlineKeyboardMarkup mainMenuKeyboard() {
        return keyboard(List.of(
                row(button("Buat Subscription Ticket KAI", "menu:new"))
        ));
    }

    // Month selection keyboard: shows from current month until December (current year).
    private InlineKeyboardMarkup monthKeyboard() {
        int currentMonth = LocalDate.now().getMonthValue();
        List<InlineKeyboardRow> rows = new ArrayList<>();
        InlineKeyboardRow row = new InlineKeyboardRow();
        for (int month = currentMonth; month <= 12; month++) {
            String label = Month.of(month).getDisplayName(TextStyle.SHORT, ID_LOCALE);
            row.add(button(label, "sm:" + month));
            // Break rows into 3 buttons per line for readability.
            if (row.size() == 3) {
                rows.add(row);
                row = new InlineKeyboardRow();
            }
        }
        // Add any remaining buttons that didn't fill a full row.
        if (!row.isEmpty()) {
            rows.add(row);
        }
        rows.add(row(button("Batal", "act:cancel")));
        return keyboard(rows);
    }

    // Start date selection keyboard for a given month.
    private InlineKeyboardMarkup startDateKeyboardForMonth(int month) {
        int year = LocalDate.now().getYear();
        YearMonth targetMonth = YearMonth.of(year, month);
        int daysInMonth = targetMonth.lengthOfMonth();
        // If selecting current month, prevent picking past days.
        int fromDay = month == LocalDate.now().getMonthValue() ? LocalDate.now().getDayOfMonth() : 1;

        List<InlineKeyboardRow> rows = new ArrayList<>();
        InlineKeyboardRow currentRow = new InlineKeyboardRow();
        for (int day = fromDay; day <= daysInMonth; day++) {
            LocalDate date = LocalDate.of(year, month, day);
            currentRow.add(button(String.valueOf(day), "sd:" + date));
            // Make each row up to 7 buttons (a "week-like" layout).
            if (currentRow.size() == 7) {
                rows.add(currentRow);
                currentRow = new InlineKeyboardRow();
            }
        }
        // Add any remaining buttons that didn't fill a full row.
        if (!currentRow.isEmpty()) {
            rows.add(currentRow);
        }
        rows.add(row(button("Batal", "act:cancel")));
        return keyboard(rows);
    }

    // End date selection keyboard: allows 0..5 days starting from the chosen start date.
    private InlineKeyboardMarkup endDateKeyboard(LocalDate startDate) {
        List<InlineKeyboardRow> rows = new ArrayList<>();
        InlineKeyboardRow row = new InlineKeyboardRow();
        int year = LocalDate.now().getYear();

        for (int i = 0; i <= 5; i++) {
            LocalDate date = startDate.plusDays(i);
            // Stop at year boundary (we only support current year in this flow).
            if (date.getYear() != year) {
                break;
            }
            row.add(button(DISPLAY_DATE.format(date), "ed:" + date));
            // Break rows into 3 buttons per line for readability.
            if (row.size() == 3) {
                rows.add(row);
                row = new InlineKeyboardRow();
            }
        }
        // Add any remaining buttons that didn't fill a full row.
        if (!row.isEmpty()) {
            rows.add(row);
        }
        rows.add(row(button("Batal", "act:cancel")));
        return keyboard(rows);
    }

    // Station selection keyboard. "prefix" controls whether buttons write org:* or dst:* callback data.
    private InlineKeyboardMarkup stationKeyboard(String prefix) {
        List<InlineKeyboardRow> rows = new ArrayList<>();
        InlineKeyboardRow row = new InlineKeyboardRow();
        for (int i = 0; i < COMMON_STATIONS.size(); i++) {
            String code = COMMON_STATIONS.get(i);
            row.add(button(code, prefix + ":" + code));
            // End row after 3 buttons or after the last station.
            if (row.size() == 3 || i == COMMON_STATIONS.size() - 1) {
                rows.add(row);
                row = new InlineKeyboardRow();
            }
        }
        rows.add(row(button("Input Manual", prefix + ":manual")));
        rows.add(row(button("Batal", "act:cancel")));
        return keyboard(rows);
    }

    // Max price selection keyboard (preset values + manual entry).
    private InlineKeyboardMarkup maxPriceKeyboard() {
        return keyboard(List.of(
                row(button("250000", "mp:250000"), button("500000", "mp:500000")),
                row(button("750000", "mp:750000"), button("1000000", "mp:1000000")),
                row(button("Input Manual", "mp:manual")),
                row(button("Batal", "act:cancel"))
        ));
    }

    // Confirmation keyboard shown before persisting the subscription.
    private InlineKeyboardMarkup confirmationKeyboard() {
        return keyboard(List.of(
                row(button("Simpan", "act:save")),
                row(button("Batal", "act:cancel"))
        ));
    }

    // Wrap rows into the Telegram markup object.
    private InlineKeyboardMarkup keyboard(List<InlineKeyboardRow> rows) {
        return new InlineKeyboardMarkup(rows);
    }

    // Creates one button with a callback payload.
    private InlineKeyboardButton button(String text, String callbackData) {
        InlineKeyboardButton button = new InlineKeyboardButton(text);
        button.setCallbackData(callbackData);
        return button;
    }

    // Convenience for building one InlineKeyboardRow from a varargs list of buttons.
    private InlineKeyboardRow row(InlineKeyboardButton... buttons) {
        InlineKeyboardRow row = new InlineKeyboardRow();
        row.addAll(List.of(buttons));
        return row;
    }

    // Telegram I/O is centralized in TelegramApiService to keep token/config/client setup in one place.
    // Sends a new message (optionally with an inline keyboard).
    private void sendMessage(String chatId, String text, InlineKeyboardMarkup markup) {
        telegramApi.sendMessage(chatId, text, markup);
    }

    // Edits an existing message; falls back to sending a new message if messageId is missing/invalid.
    private void editMessage(String chatId, Integer messageId, String text, InlineKeyboardMarkup markup) {
        telegramApi.editMessage(chatId, messageId, text, markup);
    }

    // Acknowledges a callback query to stop the client-side loading indicator.
    private void answerCallback(String callbackId) {
        telegramApi.answerCallback(callbackId);
    }

    // Normalizes station input to uppercase code form and applies basic sanity limits.
    private String normalizeStation(String value) {
        // Null input cannot be normalized.
        if (value == null) {
            return null;
        }
        String normalized = value.trim().toUpperCase();
        // Reject empty and overly long codes (basic abuse prevention).
        if (normalized.isBlank() || normalized.length() > 10) {
            return null;
        }
        return normalized;
    }

    // Parses an integer; returns -1 for invalid input to simplify validation branches.
    private int parseIntSafely(String value) {
        try {
            return Integer.parseInt(value);
        } catch (Exception e) {
            return -1;
        }
    }

    // Parses ISO-8601 LocalDate (yyyy-MM-dd) from callback payloads.
    private LocalDate parseLocalDate(String value) {
        // Reject empty values early (avoid exceptions for common cases).
        if (value == null || value.isBlank()) {
            return null;
        }
        try {
            return LocalDate.parse(value.trim());
        } catch (Exception e) {
            return null;
        }
    }
}
