package seen.kai.telegram.service;

import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;
import org.eclipse.microprofile.config.inject.ConfigProperty;
import org.jboss.logging.Logger;
import org.telegram.telegrambots.meta.api.objects.CallbackQuery;
import org.telegram.telegrambots.meta.api.objects.Update;
import org.telegram.telegrambots.meta.api.objects.replykeyboard.InlineKeyboardMarkup;
import org.telegram.telegrambots.meta.api.objects.replykeyboard.buttons.InlineKeyboardRow;
import org.telegram.telegrambots.meta.api.objects.replykeyboard.buttons.InlineKeyboardButton;
import org.telegram.telegrambots.meta.api.objects.message.Message;
import seen.kai.checker.service.StationService;
import seen.kai.subscription.dto.request.SubscriptionRequest;
import seen.kai.subscription.dto.response.SubscriptionResponse;
import seen.kai.subscription.entity.TicketSubscription;
import seen.kai.subscription.service.SubscriptionService;
import seen.kai.telegram.state.BotState;
import seen.kai.telegram.state.SubscriptionDraft;

import java.time.LocalDate;
import java.time.Month;
import java.time.YearMonth;
import java.time.format.DateTimeFormatter;
import java.time.format.TextStyle;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.Objects;
import java.util.concurrent.ConcurrentHashMap;
import java.util.regex.Pattern;

@ApplicationScoped
public class TelegramBotService {
    private static final Logger LOG = Logger.getLogger(TelegramBotService.class);
    private static final Pattern DIGITS_ONLY = Pattern.compile("^\\d+$");
    private static final List<String> COMMON_STATIONS = List.of("KEBUMEN", "PASARSENEN", "GAMBIR");
    private static final List<String> COMMON_CITIES = List.of("KEBUMEN", "YOGYAKARTA", "JAKARTA", "SURABAYA");
    private static final Locale ID_LOCALE = Locale.forLanguageTag("id-ID");
    private static final DateTimeFormatter DISPLAY_DATE = DateTimeFormatter.ofPattern("d MMM", ID_LOCALE);

    // This class is a small state machine for one Telegram chat session.
    // Updates are delivered by our webhook controller and routed to handleUpdate(...).
    private final SubscriptionService subscriptionService;
    private final StationService stationService;
    // Per chat_id draft state. Key is String (Telegram chat id), value stores the wizard progress.
    // TODO: Implement Redis For User Session
    private final ConcurrentHashMap<String, SubscriptionDraft> sessions = new ConcurrentHashMap<>();

    @Inject
    TelegramApiService telegramApi;

    @ConfigProperty(name = "kai.subscription.password", defaultValue = "")
    String subscriptionPassword;

    public TelegramBotService(SubscriptionService subscriptionService, StationService stationService) {
        this.subscriptionService = subscriptionService;
        this.stationService = stationService;
    }

    // Main entry point for webhook updates (message or callback query).
    public void handleUpdate(Update update) {
        if (update == null) {
            return;
        }

        // Handle inline keyboard button.
        if (update.hasCallbackQuery()) {
            handleCallback(update.getCallbackQuery());
            return;
        }

        // Handle regular chat messages (Text Only).
        if (update.hasMessage()) {
            handleMessage(update.getMessage());
        }
    }

    // Handles callback query updates generated by inline keyboard buttons.
    private void handleCallback(CallbackQuery callbackQuery) {
        if (callbackQuery == null || callbackQuery.getMessage() == null) return;

        String callbackData = callbackQuery.getData();
        String chatId = String.valueOf(callbackQuery.getMessage().getChatId());
        Integer messageId = callbackQuery.getMessage().getMessageId();
        answerCallback(callbackQuery.getId());

        if (chatId.isBlank() || callbackData == null || callbackData.isBlank()) return;

        if ("menu:new".equals(callbackData)) {
            handleNewSubscription(chatId, messageId);
        } else if ("act:cancel".equals(callbackData)) {
            sessions.remove(chatId);
            editMessage(chatId, messageId, "Submission subscription batal.", mainMenuKeyboard());
        } else if ("act:save".equals(callbackData)) {
            SubscriptionDraft draft = sessions.get(chatId);
            if (draft != null) saveDraft(chatId, messageId, draft);
        } else if (callbackData.startsWith("back:")) {
            handleBackState(chatId, messageId, callbackData);
        } else {
            handleCallback(chatId, messageId, callbackData);
        }
    }

    private void handleNewSubscription(String chatId, Integer messageId) {
        SubscriptionDraft draft = new SubscriptionDraft();
        if (subscriptionPassword != null && !subscriptionPassword.isBlank()) {
            draft.setState(BotState.WAITING_PASSWORD);
            draft.setPasswordVerified(false);
            sessions.put(chatId, draft);
            editMessage(chatId, messageId, "Masukkan password untuk membuat subscription:", null);
        } else {
            draft.setPasswordVerified(true);
            draft.setState(BotState.WAITING_START_MONTH);
            sessions.put(chatId, draft);
            editMessage(chatId, messageId, "Pilih bulan mulai:", monthKeyboard());
        }
    }

    private void handleBackState(String chatId, Integer messageId, String callbackData) {
        SubscriptionDraft draft = sessions.get(chatId);
        if (draft == null) return;

        switch (callbackData) {
            case "back:month" -> {
                draft.setState(BotState.WAITING_START_MONTH);
                editMessage(chatId, messageId, "Pilih bulan mulai:", monthKeyboard());
            }
            case "back:sd" -> {
                draft.setState(BotState.WAITING_START_DATE);
                editMessage(chatId, messageId, "Pilih tanggal mulai:", startDateKeyboardForMonth(draft.getStartMonth(), "back:month"));
            }
            case "back:org" -> {
                draft.setState(BotState.WAITING_DEPARTURE_CITY);
                editMessage(chatId, messageId, "Pilih Kota Asal :", cityKeyboard("dcity", "back:ed"));
            }
            case "back:dst" -> {
                draft.setState(BotState.WAITING_ARRIVAL_CITY);
                editMessage(chatId, messageId, "Pilih Kota Tujuan :", cityKeyboard("acity", "back:org_select"));
            }
            case "back:ed" -> {
                draft.setState(BotState.WAITING_END_DATE);
                editMessage(chatId, messageId, "Pilih tanggal akhir (maks 5 hari):", endDateKeyboard(draft.getStartDate(), "back:sd"));
            }
            case "back:org_select" -> {
                draft.setState(BotState.WAITING_ORIGINATION);
                editMessage(chatId, messageId, "Pilih Stasiun Keberangkatan :", stationKeyboard("org", draft.getDepartureStations(), "back:org"));
            }
            case "back:dst_select" -> {
                draft.setState(BotState.WAITING_DESTINATION);
                editMessage(chatId, messageId, "Pilih Stasiun Tujuan :", stationKeyboard("dst", draft.getArrivalStations(), "back:dst"));
            }
            case "back:mp_select" -> {
                draft.setState(BotState.WAITING_MAX_PRICE);
                editMessage(chatId, messageId, "Pilih maksimal harga :", maxPriceKeyboard("back:dst_select"));
            }
        }
    }

    private void handleCallback(String chatId, Integer messageId, String callbackData) {
        SubscriptionDraft draft = sessions.computeIfAbsent(chatId, ignored -> new SubscriptionDraft());

        if (callbackData.startsWith("sm:")) {
            handleMonthSelection(chatId, messageId, draft, callbackData);
        } else if (callbackData.startsWith("sd:")) {
            handleStartDateSelection(chatId, messageId, draft, callbackData);
        } else if (callbackData.startsWith("ed:")) {
            handleEndDateSelection(chatId, messageId, draft, callbackData);
        } else if (callbackData.startsWith("dcity:")) {
            handleDepartureCitySelection(chatId, messageId, draft, callbackData);
        } else if (callbackData.startsWith("org:")) {
            handleOriginationSelection(chatId, messageId, draft, callbackData);
        } else if (callbackData.startsWith("acity:")) {
            handleArrivalCitySelection(chatId, messageId, draft, callbackData);
        } else if (callbackData.startsWith("dst:")) {
            handleDestinationSelection(chatId, messageId, draft, callbackData);
        } else if (callbackData.startsWith("mp:")) {
            handleMaxPriceSelection(chatId, messageId, draft, callbackData);
        }
    }

    private void handleMonthSelection(String chatId, Integer messageId, SubscriptionDraft draft, String data) {
        int month = parseIntSafely(data.substring(3));
        int currentMonth = LocalDate.now().getMonthValue();
        if (month < currentMonth || month > 12) {
            editMessage(chatId, messageId, "Bulan tidak valid.", monthKeyboard());
            return;
        }
        draft.setStartMonth(month);
        draft.setState(BotState.WAITING_START_DATE);
        editMessage(chatId, messageId, "Pilih tanggal mulai:", startDateKeyboardForMonth(month, "back:month"));
    }

    private void handleStartDateSelection(String chatId, Integer messageId, SubscriptionDraft draft, String data) {
        LocalDate startDate = parseLocalDate(data.substring(3));
        if (startDate == null || startDate.getYear() != LocalDate.now().getYear() || startDate.isBefore(LocalDate.now())) {
            editMessage(chatId, messageId, "Tanggal mulai tidak valid.", monthKeyboard());
            return;
        }
        draft.setStartDate(startDate);
        draft.setState(BotState.WAITING_END_DATE);
        editMessage(chatId, messageId, "Pilih tanggal akhir (maks 5 hari):", endDateKeyboard(startDate, "back:sd"));
    }

    private void handleEndDateSelection(String chatId, Integer messageId, SubscriptionDraft draft, String data) {
        LocalDate endDate = parseLocalDate(data.substring(3));
        LocalDate startDate = draft.getStartDate();
        if (endDate == null || startDate == null) {
            editMessage(chatId, messageId, "Tanggal akhir tidak valid.", monthKeyboard());
            return;
        }
        if (endDate.isBefore(startDate) || endDate.isAfter(startDate.plusDays(5)) || endDate.getYear() != LocalDate.now().getYear()) {
            editMessage(chatId, messageId, "Tanggal akhir harus dalam rentang 0..5 hari dari tanggal mulai.", endDateKeyboard(startDate, "back:sd"));
            return;
        }
        draft.setEndDate(endDate);
        draft.setState(BotState.WAITING_DEPARTURE_CITY);
        editMessage(chatId, messageId, "Pilih Kota Asal :", cityKeyboard("dcity", "back:ed"));
    }

    private void handleDepartureCitySelection(String chatId, Integer messageId, SubscriptionDraft draft, String data) {
        if ("dcity:manual".equals(data)) {
            draft.setState(BotState.WAITING_DEPARTURE_CITY_TEXT);
            editMessage(chatId, messageId, "Ketik Kota Asal (contoh: YOGYAKARTA).", null);
            return;
        }
        String cityName = data.substring(6).trim().toUpperCase(Locale.ROOT);
        List<StationService.Station> stations = stationService.findStationNamesByCityName(cityName);
        draft.setDepartureStations(stations);
        draft.setState(BotState.WAITING_ORIGINATION);
        editMessage(chatId, messageId, "Pilih Stasiun Keberangkatan :", stationKeyboard("org", stations, "back:org"));
    }

    private void handleOriginationSelection(String chatId, Integer messageId, SubscriptionDraft draft, String data) {
        String code = data.substring(4).trim().toUpperCase(Locale.ROOT);
        StationService.Station station = stationService.findAllStationsByName(code).orElse(null);
        draft.setOrigination(station != null ? station.code() : code);
        draft.setState(BotState.WAITING_ARRIVAL_CITY);
        editMessage(chatId, messageId, "Pilih Stasiun Tujuan :", cityKeyboard("acity", "back:org_select"));
    }

    private void handleArrivalCitySelection(String chatId, Integer messageId, SubscriptionDraft draft, String data) {
        String cityName = data.substring(6).trim().toUpperCase(Locale.ROOT);
        List<StationService.Station> stations = stationService.findStationNamesByCityName(cityName);
        draft.setArrivalStations(stations);
        draft.setState(BotState.WAITING_DESTINATION);
        editMessage(chatId, messageId, "Pilih Stasiun Tujuan :", stationKeyboard("dst", stations, "back:dst"));
    }

    private void handleDestinationSelection(String chatId, Integer messageId, SubscriptionDraft draft, String data) {
        String code = data.substring(4).trim().toUpperCase(Locale.ROOT);
        StationService.Station station = stationService.findAllStationsByName(code).orElse(null);
        draft.setDestination(station != null ? station.code() : code);
        draft.setState(BotState.WAITING_MAX_PRICE);
        editMessage(chatId, messageId, "Pilih maksimal harga :", maxPriceKeyboard("back:dst_select"));
    }

    private void handleMaxPriceSelection(String chatId, Integer messageId, SubscriptionDraft draft, String data) {
        if ("mp:manual".equals(data)) {
            draft.setState(BotState.WAITING_MAX_PRICE);
            editMessage(chatId, messageId, "Ketik maksimal harga (contoh: 350000).", null);
            return;
        }
        int maxPrice = parseIntSafely(data.substring(3));
        if (maxPrice <= 0) {
            editMessage(chatId, messageId, "Maksimal harga tidak valid. Pilih tombol atau ketik angka.", maxPriceKeyboard("back:dst_select"));
            return;
        }
        draft.setMaxPrice(maxPrice);
        draft.setState(BotState.WAITING_CONFIRMATION);
        editMessage(chatId, messageId, buildSummary(draft), confirmationKeyboard("back:mp_select"));
    }

    // Handles regular chat messages.
    private void handleMessage(Message message) {
        if (message == null || message.getChatId() == null || message.getText() == null) return;

        String chatId = String.valueOf(message.getChatId());
        String text = message.getText().trim();
        if (text.isBlank()) return;

        if (text.startsWith("/")) {
            handleCommand(chatId, text);
        } else {
            handleStateMessage(chatId, text);
        }
    }

    private void handleCommand(String chatId, String text) {
        if ("/start".equalsIgnoreCase(text)) {
            sessions.remove(chatId);
            sendMessage(chatId, "Pilih menu:", mainMenuKeyboard());
        } else if ("/delete".equalsIgnoreCase(text)) {
            handleDeleteCommand(chatId);
        } else if ("/list".equalsIgnoreCase(text)) {
            handleListCommand(chatId);
        } else if ("/cancel".equalsIgnoreCase(text)) {
            sessions.remove(chatId);
            sendMessage(chatId, "Flow dibatalkan.", mainMenuKeyboard());
        } else if ("/new".equalsIgnoreCase(text)) {
            handleNewSubscription(chatId, null); // Uses sendMessage inside via indirect flow if needed, but menu:new is preferred
        }
    }

    private void handleDeleteCommand(String chatId) {
        if (subscriptionPassword == null || subscriptionPassword.isBlank()) {
            sendMessage(chatId, "Delete dinonaktifkan: server belum set kai.subscription.password.", null);
            return;
        }
        List<TicketSubscription> subscriptions = subscriptionService.findAllByChatId(chatId);
        if (subscriptions.isEmpty()) {
            sendMessage(chatId, "Tidak ada subscription untuk chat ini.", mainMenuKeyboard());
            return;
        }
        TicketSubscription target = subscriptions.getFirst();
        SubscriptionDraft draft = new SubscriptionDraft();
        draft.setState(BotState.WAITING_DELETE_PASSWORD);
        draft.setPasswordVerified(false);
        draft.setPendingDeleteSubscriptionId(target.getId());
        draft.setPendingDeleteSummary(buildSubscriptionSummary(target));
        sessions.put(chatId, draft);
        sendMessage(chatId, "Masukkan password untuk menghapus subscription ini:\n\n" + draft.getPendingDeleteSummary(), null);
    }

    private void handleListCommand(String chatId) {
        List<TicketSubscription> subscriptions = subscriptionService.findAllByChatId(chatId);
        if (subscriptions.isEmpty()) {
            sendMessage(chatId, "Tidak ada subscription untuk chat ini.", mainMenuKeyboard());
            return;
        }
        StringBuilder out = new StringBuilder("Daftar subscription (" + chatId + "):\n\n");
        for (TicketSubscription sub : subscriptions) {
            out.append(buildSubscriptionSummary(sub)).append("\n\n");
        }
        sendMessage(chatId, out.toString().trim(), mainMenuKeyboard());
    }

    private void handleStateMessage(String chatId, String text) {
        SubscriptionDraft draft = sessions.get(chatId);
        if (draft == null) {
            sendMessage(chatId, "Ketik /new untuk buat subscription baru.", mainMenuKeyboard());
            return;
        }

        switch (draft.getState()) {
            case WAITING_DELETE_PASSWORD -> handleDeletePassword(chatId, draft, text);
            case WAITING_PASSWORD -> handleCreatePassword(chatId, draft, text);
            case WAITING_DEPARTURE_CITY_TEXT -> handleCityText(chatId, draft, text, true);
            case WAITING_ARRIVAL_CITY_TEXT -> handleCityText(chatId, draft, text, false);
            case WAITING_MAX_PRICE -> handleMaxPriceText(chatId, draft, text);
            default -> sendMessage(chatId, "Input tidak sesuai state saat ini. Gunakan tombol atau /cancel.", null);
        }
    }

    private void handleDeletePassword(String chatId, SubscriptionDraft draft, String text) {
        if (subscriptionPassword != null && subscriptionPassword.equals(text)) {
            Long id = draft.getPendingDeleteSubscriptionId();
            boolean deleted = id != null && id > 0 ? subscriptionService.deleteForChatId(id, chatId) : subscriptionService.deleteForChatId(chatId);
            sessions.remove(chatId);
            if (!deleted) {
                sendMessage(chatId, "Gagal delete: subscription tidak ditemukan.", mainMenuKeyboard());
            } else {
                sendMessage(chatId, "Subscription terhapus:\n\n" + (draft.getPendingDeleteSummary() != null ? draft.getPendingDeleteSummary() : "Berhasil."), mainMenuKeyboard());
            }
        } else {
            sendMessage(chatId, "Password salah. Coba lagi atau /cancel.", null);
        }
    }

    private void handleCreatePassword(String chatId, SubscriptionDraft draft, String text) {
        if (subscriptionPassword != null && subscriptionPassword.equals(text)) {
            draft.setPasswordVerified(true);
            draft.setState(BotState.WAITING_START_MONTH);
            sendMessage(chatId, "Password OK. Pilih bulan mulai (tahun otomatis):", monthKeyboard());
        } else {
            sendMessage(chatId, "Password salah. Coba lagi atau /cancel.", null);
        }
    }

    private void handleCityText(String chatId, SubscriptionDraft draft, String text, boolean isDeparture) {
        String cityName = normalizeStation(text);
        if (cityName == null) {
            sendMessage(chatId, "Nama Kota tidak valid.", null);
            return;
        }
        List<String> matches = stationService.findAllCityNames().stream().filter(c -> c.contains(cityName)).toList();
        if (matches.isEmpty()) {
            String msg = "Nama Kota " + cityName + " tidak ditemukan di KAI. Ketik ulang atau pilih yang tersedia.";
            sendMessage(chatId, msg, cityKeyboard(isDeparture ? "dcity" : "acity", isDeparture ? "back:ed" : "back:org_select"));
            return;
        }
        List<StationService.Station> stations = stationService.findStationNamesByCityName(cityName);
        if (isDeparture) {
            draft.setDepartureStations(stations);
            draft.setState(BotState.WAITING_ORIGINATION);
            sendMessage(chatId, "Pilih Stasiun Asal:", stationKeyboard("org", stations, "back:org"));
        } else {
            draft.setArrivalStations(stations);
            draft.setState(BotState.WAITING_DESTINATION);
            sendMessage(chatId, "Pilih Stasiun Tujuan:", stationKeyboard("dst", stations, "back:dst"));
        }
    }

    private void handleMaxPriceText(String chatId, SubscriptionDraft draft, String text) {
        if (DIGITS_ONLY.matcher(text).matches()) {
            int value = parseIntSafely(text);
            if (value > 0) {
                draft.setMaxPrice(value);
                draft.setState(BotState.WAITING_CONFIRMATION);
                sendMessage(chatId, buildSummary(draft), confirmationKeyboard("back:mp_select"));
                return;
            }
        }
        sendMessage(chatId, "Input tidak valid. Ketik angka harga maksimal atau /cancel.", null);
    }

    // Persists the draft as a subscription (create new or attach chat to existing subscription).
    private void saveDraft(String chatId, Integer messageId, SubscriptionDraft draft) {
        try {
            // If password is configured, require it to have been verified in the wizard.
            if (subscriptionPassword != null && !subscriptionPassword.isBlank() && !draft.isPasswordVerified()) {
                editMessage(chatId, messageId, "Password belum diverifikasi. Ketik /new untuk mulai lagi.", mainMenuKeyboard());
                return;
            }
            // Build request DTO and delegate persistence/validation to SubscriptionService.
            SubscriptionRequest request = new SubscriptionRequest(
                    draft.getStartDate(),
                    draft.getEndDate(),
                    draft.getOrigination(),
                    draft.getDestination(),
                    draft.getMaxPrice(),
                    chatId,
                    subscriptionPassword
            );
            SubscriptionResponse response = subscriptionService.createOrAttach(request);
            // Clear wizard session after successful save.
            sessions.remove(chatId);
            editMessage(
                    chatId,
                    messageId,
                    "Subscription tersimpan.\n"
                            + "ID: " + response.id() + "\n"
                            + "Rute: " + response.origination() + " -> " + response.destination() + "\n"
                            + "Rentang tanggal: " + response.startDate() + " s/d " + response.endDate() + "\n"
                            + "Max price: " + response.maxPrice(),
                    mainMenuKeyboard()
            );
        } catch (IllegalArgumentException e) {
            // Validation / business rule errors are shown to user.
            LOG.error("Gagal simpan ", e);
            editMessage(chatId, messageId, "Gagal simpan: " + e.getMessage(), confirmationKeyboard("back:mp_select"));
        } catch (Exception e) {
            // Unexpected errors should be logged server-side; user gets a generic message.
            LOG.error("Gagal simpan subscription dari Telegram bot", e);
            editMessage(chatId, messageId, "Terjadi error saat simpan subscription.", confirmationKeyboard("back:mp_select"));
        }
    }

    // Builds a short confirmation text shown before the user presses "Simpan".
    private String buildSummary(SubscriptionDraft draft) {
        return "Konfirmasi subscription:\n"
                + "start_date: " + draft.getStartDate() + "\n"
                + "end_date: " + draft.getEndDate() + "\n"
                + "origination: " + draft.getOrigination() + "\n"
                + "destination: " + draft.getDestination() + "\n"
                + "max_price: " + draft.getMaxPrice();
    }

    // Builds a compact summary used for delete confirmation.
    private String buildSubscriptionSummary(TicketSubscription subscription) {
        return "ID: " + subscription.getId() + "\n"
                + "Tanggal: " + subscription.getStartDate() + " s/d " + subscription.getEndDate() + "\n"
                + "Rute: " + subscription.getOrigination() + " -> " + subscription.getDestination() + "\n"
                + "Max price: " + subscription.getMaxPrice();
    }

    // Inline keyboard helpers.
    // telegrambots-meta 9.5.0 models keyboards as List<InlineKeyboardRow> (not List<List<Button>>).
    // Main menu keyboard shown on /start and after successful operations.
    private InlineKeyboardMarkup mainMenuKeyboard() {
        return keyboard(List.of(
                row(button("Buat Subscription Ticket KAI", "menu:new"))
        ));
    }

    // Month selection keyboard: shows from current month until December (current year).
    private InlineKeyboardMarkup monthKeyboard() {
        int currentMonth = LocalDate.now().getMonthValue();
        List<InlineKeyboardRow> rows = new ArrayList<>();
        InlineKeyboardRow row = new InlineKeyboardRow();
        for (int month = currentMonth; month <= 12; month++) {
            String label = Month.of(month).getDisplayName(TextStyle.SHORT, ID_LOCALE);
            row.add(button(label, "sm:" + month));
            // Break rows into 3 buttons per line for readability.
            if (row.size() == 3) {
                rows.add(row);
                row = new InlineKeyboardRow();
            }
        }
        // Add any remaining buttons that didn't fill a full row.
        if (!row.isEmpty()) {
            rows.add(row);
        }
        rows.add(row(button("Batal", "act:cancel")));
        return keyboard(rows);
    }

    // Start date selection keyboard for a given month.
    private InlineKeyboardMarkup startDateKeyboardForMonth(int month, String backState) {
        int year = LocalDate.now().getYear();
        YearMonth targetMonth = YearMonth.of(year, month);
        int daysInMonth = targetMonth.lengthOfMonth();
        // If selecting current month, prevent picking past days.
        int fromDay = month == LocalDate.now().getMonthValue() ? LocalDate.now().getDayOfMonth() : 1;

        List<InlineKeyboardRow> rows = new ArrayList<>();
        InlineKeyboardRow currentRow = new InlineKeyboardRow();
        for (int day = fromDay; day <= daysInMonth; day++) {
            LocalDate date = LocalDate.of(year, month, day);
            currentRow.add(button(String.valueOf(day), "sd:" + date));
            // Make each row up to 7 buttons (a "week-like" layout).
            if (currentRow.size() == 7) {
                rows.add(currentRow);
                currentRow = new InlineKeyboardRow();
            }
        }
        // Add any remaining buttons that didn't fill a full row.
        if (!currentRow.isEmpty()) {
            rows.add(currentRow);
        }
        if (backState != null && !backState.isBlank()) {
            rows.add(row(button("Kembali", backState)));
        }
        rows.add(row(button("Batal", "act:cancel")));
        return keyboard(rows);
    }

    // End date selection keyboard: allows 0..5 days starting from the chosen start date.
    private InlineKeyboardMarkup endDateKeyboard(LocalDate startDate, String backState) {
        List<InlineKeyboardRow> rows = new ArrayList<>();
        InlineKeyboardRow row = new InlineKeyboardRow();
        int year = LocalDate.now().getYear();

        for (int i = 0; i <= 5; i++) {
            LocalDate date = startDate.plusDays(i);
            // Stop at year boundary (we only support current year in this flow).
            if (date.getYear() != year) {
                break;
            }
            row.add(button(DISPLAY_DATE.format(date), "ed:" + date));
            // Break rows into 3 buttons per line for readability.
            if (row.size() == 3) {
                rows.add(row);
                row = new InlineKeyboardRow();
            }
        }
        // Add any remaining buttons that didn't fill a full row.
        if (!row.isEmpty()) {
            rows.add(row);
        }
        if (backState != null && !backState.isBlank()) {
            rows.add(row(button("Kembali", backState)));
        }
        rows.add(row(button("Batal", "act:cancel")));
        return keyboard(rows);
    }

    private InlineKeyboardMarkup cityKeyboard(String prefix, String backState) {
        List<InlineKeyboardRow> rows = new ArrayList<>();
        InlineKeyboardRow row = new InlineKeyboardRow();
        for (int i = 0; i < COMMON_CITIES.size(); i++) {
            String code = COMMON_CITIES.get(i);
            row.add(button(code, prefix + ":" + code));
            // End row after 2 buttons or after the last station.
            if (row.size() == 2 || i == COMMON_CITIES.size() - 1) {
                rows.add(row);
                row = new InlineKeyboardRow();
            }
        }
        rows.add(row(button("Input Manual", prefix + ":manual")));
        if (backState != null && !backState.isBlank()) {
            rows.add(row(button("Kembali", backState)));
        }
        rows.add(row(button("Batal", "act:cancel")));
        return keyboard(rows);
    }

    // Station selection keyboard. "prefix" controls whether buttons write org:* or dst:* callback data.
    private InlineKeyboardMarkup stationKeyboard(String prefix, List<StationService.Station> stations, String backState) {
        List<InlineKeyboardRow> rows = new ArrayList<>();
        InlineKeyboardRow row = new InlineKeyboardRow();

        if (stations != null && !stations.isEmpty()) {
            for (StationService.Station station : stations) {
                row.add(button(station.name(), prefix + ":" + station.name()));
                if (row.size() == 2 || Objects.equals(station, stations.getLast())) {
                    rows.add(row);
                    row = new InlineKeyboardRow();
                }
            }
        } else {
            for (int i = 0; i < COMMON_STATIONS.size(); i++) {
                String code = COMMON_STATIONS.get(i);
                row.add(button(code, prefix + ":" + code));
                // End row after 2 buttons or after the last station.
                if (row.size() == 2 || i == COMMON_STATIONS.size() - 1) {
                    rows.add(row);
                    row = new InlineKeyboardRow();
                }
            }
        }

//        rows.add(row(button("Input Manual", prefix + ":manual")));
        if (backState != null && !backState.isBlank()) {
            rows.add(row(button("Kembali", backState)));
        }
        rows.add(row(button("Batal", "act:cancel")));
        return keyboard(rows);
    }

    // Max price selection keyboard (preset values + manual entry).
    private InlineKeyboardMarkup maxPriceKeyboard(String backState) {
        List<InlineKeyboardRow> rows = new ArrayList<>(List.of(
                row(button("250000", "mp:250000"), button("500000", "mp:500000")),
                row(button("750000", "mp:750000"), button("1000000", "mp:1000000")),
                row(button("Input Manual", "mp:manual"))
        ));
        if (backState != null && !backState.isBlank()) {
            rows.add(row(button("Kembali", backState)));
        }
        rows.add(row(button("Batal", "act:cancel")));
        return keyboard(rows);
    }

    // Confirmation keyboard shown before persisting the subscription.
    private InlineKeyboardMarkup confirmationKeyboard(String backState) {
        List<InlineKeyboardRow> rows = new ArrayList<>(List.of(
                row(button("Simpan", "act:save"))
        ));
        if (backState != null && !backState.isBlank()) {
            rows.add(row(button("Kembali", backState)));
        }
        rows.add(row(button("Batal", "act:cancel")));
        return keyboard(rows);
    }

    // Wrap rows into the Telegram markup object.
    private InlineKeyboardMarkup keyboard(List<InlineKeyboardRow> rows) {
        return new InlineKeyboardMarkup(rows);
    }

    // Creates one button with a callback payload.
    private InlineKeyboardButton button(String text, String callbackData) {
        InlineKeyboardButton button = new InlineKeyboardButton(text);
        button.setCallbackData(callbackData);
        return button;
    }

    // Convenience for building one InlineKeyboardRow from a varargs list of buttons.
    private InlineKeyboardRow row(InlineKeyboardButton... buttons) {
        InlineKeyboardRow row = new InlineKeyboardRow();
        row.addAll(List.of(buttons));
        return row;
    }

    // Telegram I/O is centralized in TelegramApiService to keep token/config/client setup in one place.
    // Sends a new message (optionally with an inline keyboard).
    private void sendMessage(String chatId, String text, InlineKeyboardMarkup markup) {
        telegramApi.sendMessage(chatId, text, markup);
    }

    // Edits an existing message; falls back to sending a new message if messageId is missing/invalid.
    private void editMessage(String chatId, Integer messageId, String text, InlineKeyboardMarkup markup) {
        telegramApi.editMessage(chatId, messageId, text, markup);
    }

    // Acknowledges a callback query to stop the client-side loading indicator.
    private void answerCallback(String callbackId) {
        telegramApi.answerCallback(callbackId);
    }

    // Normalizes station input to uppercase code form and applies basic sanity limits.
    private String normalizeStation(String value) {
        // Null input cannot be normalized.
        if (value == null) {
            return null;
        }
        String normalized = value.trim().toUpperCase();
        // Reject empty and overly long codes (basic abuse prevention).
        if (normalized.isBlank() || normalized.length() > 10) {
            return null;
        }
        return normalized;
    }

    // Parses an integer; returns -1 for invalid input to simplify validation branches.
    private int parseIntSafely(String value) {
        try {
            return Integer.parseInt(value);
        } catch (Exception e) {
            return -1;
        }
    }

    // Parses ISO-8601 LocalDate (yyyy-MM-dd) from callback payloads.
    private LocalDate parseLocalDate(String value) {
        // Reject empty values early (avoid exceptions for common cases).
        if (value == null || value.isBlank()) {
            return null;
        }
        try {
            return LocalDate.parse(value.trim());
        } catch (Exception e) {
            return null;
        }
    }
}
